version: '3.1'

services:
  db:
    image: mongo:7.0.11
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: pokemon-nest
    volumes: 
      - ./mongo:/data/db